const scheduleData = [
    {id: 1,
        col1: "8:00-9:00",
        col2: "Physics",
        col3: "Physics",
        col4: "Physics",
        col5: "Physics",
        col6: "Physics",
      },
      {
        id: 2,
        col1: "9:00-10:00",
        col2: "Physics",
        col3: "Physics",
        col4: "Physics",
        col5: "Physics",
        col6: "Physics",
      },
      {
        id: 3,
        col1: "10:00-11:00",
        col2: "Physics",
        col3: "Physics",
        col4: "Physics",
        col5: "Physics",
        col6: "Physics",
      },
      {
        id: 4,
        col1: "11:00-12:00",
        col2: "Break",
        col3: "Break",
        col4: "Break",
        col5: "Break",
        col6: "Break",
      },
      {
        id: 5,
        col1: "12:00-13:00",
        col2: "Physics",
        col3: "Physics",
        col4: "Physics",
        col5: "Physics",
        col6: "Physics",
      },
      {
        id: 6,
        col1: "13:00-14:00",
        col2: "Physics",
        col3: "Physics",
        col4: "Physics",
        col5: "Physics",
        col6: "Physics",
      },
      {
        id: 7,
        col1: "14:00-15:00",
        col2: "Physics",
        col3: "Physics",
        col4: "Physics",
        col5: "Physics",
        col6: "Physics",
      },
  ];
  
  export default scheduleData;